// Arts //
const d1 = 'What are the subjects in the Arts Stream? The major subjects in the Arts Stream include Economics, History, Political Science, Geography, Sociology, Philosophy, Psychology, Computer Science, Hindi, Regional language, etc. From Law and Literary Studies to Journalism and Hotel Management, careers after Arts stream are copious. Moreover, the stream of Arts and Humanities offers a greater variety of subjects than the Science and Commerce stream. Want to know which job is the best after 12th Arts? Read this blog to find all the arts stream subjects, courses, jobs and salaries in 2023.';
const d2 = 'If you are wondering “How many subjects are there in art class 11?“, there are numerous subjects in Class 11 Arts such as Geography, History, Political Science, Economics, Psychology and more. Here are the major arts stream subjects in 11th:';
const d3 = '1.Psychology \n2.Sociology \n3.Philosophy \n4.Music \n5.Human Rights and Gender Studies\n6.Informatics Practices\n7.Public Administration\n8.History\n9.Economics\n10.Geography\n11.Political Science\n12.English\n13.Home Science\n14.Legal Studies\n15.Mass Media Studies\n16.Entrepreneurship\n17.Physical Education\n18.Fashion Studies\n19.Fine Arts';

// Commerce //
const d4 = 'Commerce is an excellent stream to get into; there is a lot of practical knowledge to be gained from this subject. Even if you were to become a part of a commerce business, you would still need to understand how the industry works. Students in the 11th and 12th classes will already have a good head start in this field when selecting a course for their graduation in this field. There is a lot of potential in Commerce. You could become an entrepreneur or a business owner or even become a part of a commerce company and help it grow.';
const d5 = 'Accountancy (mandatory)\nBusiness Studies (mandatory)\nEconomics (mandatory)\nEnglish (mandatory)\nMathematics (optional)\nPhysica\nEducation (optional)';

// Science //
const d6 = 'The first and foremost of many major career-related decisions you will make is selecting a Sceince subject stream for Class 11th and 12th. After spending your prior years in a school studying a wide range of subjects, this is the moment when you have to choose a specialised stream that best meets your interests, abilities, and career aspirations. Don\'t worry if you haven\'t yet defined a specific career objective; there is still plenty of time to do so.';
const d7 = 'While choosing a stream is easier than choosing a career, it is still important to make an informed decision because your stream might influence your entire career. After Class 10th, there are three main streams to choose from Science, Commerce, and Humanities/Arts, each with its concepts and theories, methodologies, subject possibilities, and career options.';
const d8 = 'Science comprises scientific theories and applications, whereas Commerce comprises trade and business, and Humanities involve the liberal arts.';
const d9 = 'In this blog, we will focus on the 11th science subject. Knowing what knowledge each subject offers will be of great assistance to you. So let\'s discuss the 11th science subject.';
const d10 = 'Physics is the science that includes matter, motion, energy, and force, and it is one of the world\'s oldest-studied academic areas. It focuses on figuring out how things work and function and come in contact to generate more energy for further motions. Physics advancements, such as studying electromagnetic, thermodynamics, mechanics, nuclear physics, and solid-state physics, have enabled tremendous technological improvements. Physics in the 11th and 12th grades aids in developing observational, analytical, investigative, and decision-making skills, as well as conceptual comprehension, creative thinking, and problem-solving abilities.';
const d11 = 'Everything in the universe is made up of atoms and matter, and chemistry studies matter\'s composition, properties, and structure, including atomic structure and chemical reaction modifications. In class 11th and 12th level, new areas of chemistry, such as synthetic materials, natural resources, biomolecules, and industrial chemistry, are also covered, ensuring that you have a complete understanding of Chemistry basics and current advancements. Practical lab experiments will bolster your theoretical studies.';
const d12 = 'The term "biology" comes from the Greek language where "bios" means "life" and "logos" means "study," therefore it means "study of life forms." That is precisely what biology is. Biology examines the physical structures, physiological systems, chemical processes, molecular interactions, and development and evolution of living species, including plants and animals. Biology is a subject taught in grades 11th and 12th that focuses on establishing a solid conceptual foundation while connecting the subject with real-world technological advancements, including agriculture, health, and industry.';
const d13 = 'Mathematics is a science of numbers that is the most apprehensive though the most appreciated subject among students, with applications in everything from money transactions to architecture, art, engineering, and sports. Maths focuses on the concepts of amount, geometry, calculations, change, structure, space, etc. You study the concepts of underlying processes and skills in Class 11th -12th, how to work with calculations and reason while solving a problem or proving a result, and how to apply gained skills to solve problems using several methods. You must choose Mathematics as another major subject if you are pursuing the Medical stream in Sciences (PCB).';
const d14 = 'English is a compulsory subject taught in Classes 11th and 12th regardless of the stream because it is one of India\'s official languages and the most widely spoken language on the planet. Considering that English is a widely used language across India, especially in offices, colleges, and online, having a basic understanding of the language is always beneficial.The concepts in English focus on improving one\'s reading, writing, grammar, and listening/speaking skills in English in classes 11th and 12th, preparing students for higher studies and immediate employment. Studying English will also help you improve your general communication and comprehension abilities, which will be useful in almost any career where English is the primary language of communication. Mass communication, journalism, teaching, public relations, and blogging are all possible career paths after learning English.';

// Diploma //
const d15 = 'Diploma courses after 10th list include various fields such as Engineering, IT, Marketing, Graphics, Commerce, Fashion Designing, etc. These are just a few of the many different diploma courses that are available to students once they have completed the 10th class. Your personal interests and professional goals will help establish the strategy that will work best for you. If you are undecided about what you want to do when you complete the 10th, you should seriously consider enrolling in a foundation course.';
const d16 = 'Diploma in Engineering\nDiploma in Hotel Management\nDiploma in Journalism\nDiploma in Education\nDiploma in Photography\nDiploma in Psychology\nDiploma in Elementary Education\nDiploma in Digital Marketing\nDiploma in Fine Arts\nDiploma in English\nDiploma in Fashion Designing\nDiploma in Graphic Designing\nDiploma in Web Development\nDiploma in Web Designing\nDiploma in Game Designing\nDiploma in Bakery & Confectionery\nDiploma in Hotel Reception & Book-keeping\nDiploma in Food Technology\nDiploma in Information Technology\nDiploma in Makeup and Beauty\nDiploma in Event Management\nDiploma in Business Management\nDiploma in Marine Engineering\nDiploma in Animation\nDiploma in Textile Designing\nDiploma in Leather Designing\nDiploma in Textile Engineering';
const d17 = 'Further, while looking for the best course after the 10th, here is a list of the top programs and courses after the 10th:';
const d18 = 'Diploma in Fine Arts \nDiploma in Commercial Art\nDiploma in Graphic Designing\nCertificate Course in Spoken English\nCertificate Course in Functional English\nDiploma in Social Media Management\nDiploma in Hotel Management\nCertificate in Hindi ';
const d19 = 'Certificate in Animation\nCertificate Course in Tally\nDiploma in Banking\nDiploma in Risk and Insurance\nDiploma in Computer Application\nAdvanced Diploma in Financial Accounting\nDiploma in e-Accounting Taxation';
const d20 = 'Diploma in Information Technology\nCraftsmanship Course in Food Production\nCertificate in Diesel Mechanics\nDiploma in Dental Mechanics\nDiploma in Dental Hygienist\nDiploma in Electrical Engineering\nDiploma in Computer Science and Engineering';
const d21 = 'The field of Computer and Information Technology comprises a wide range of training and skill development courses after the 10th that senior secondary students can pursue. These programs majorly include certification courses that equip students with theoretical knowledge as well as extensive industry exposure. So, if you are wondering about how to do computer science after the 10th then let’s take a look at the following list of courses after the 10th standard under IT and Computer Technology';
const d22 = 'Diploma in Computer Application\nCertificate in Social Media Management\nDiploma in Hardware Maintenance\nCertificate Course in Search Engine Marketing\nComputer Technician Diploma\nCertificate in Search Engine Optimisation\nCertificate in Graphic/Web Design\nCertificate Course in Programming Language';


// 'Polytechnic Courses'//
const p1 = 'What is Polytechnic: Course Details, Fees, Eligibility, Admission Process, Career';
const p2 = 'If you are looking for information about Polytechnic courses, you have come to the right place. Polytechnic courses are diploma or vocational qualifications that focus on providing technical education. These courses last for three years and upon completion, successful students will receive a diploma certificate.';
const p3 = 'Polytechnic courses provide a pathway for students to launch their careers in various engineering specializations. Many top educational institutions offer diploma courses in multiple BTech disciplines. To be eligible for admission to the polytechnic course, candidates must have scored a minimum of 40% marks in their last qualifying examination with English, Mathematics, and Science as compulsory subjects.';
const p4 = 'Admission to polytechnic courses is based on merit and entrance examinations. Popular exams for this level include AP POLYCET, TS POLYCET, CG PPT, JEXPO, and JEECUP. Government Polytechnic (GP), V.P.M.’s Polytechnic, S.H. Jondhale Polytechnic (SHJP), and Government Women Polytechnic College (GWPC) are among the commonly renowned institutes offering these courses. Polytechnic course fees range from Rs. 15k to Rs. 500k depending on the institution chosen.';
const p5 = 'Qualification : Should have passed class 10th or 12th\nMinimum Marks : Candidates should have obtained 40% marks in the qualifying examination. (Note: Minimum marks can vary from institute to institute)\nNationality : Should be of Indian National \n Compulsory Subjects : Generally Mathematics, Science & English are considered to be compulsory polytechnic subjects to apply for diploma courses.';

// Medical & Paramedical //
const p6 = 'Paramedical courses have become widely popular in the past few years. These courses are a vital part of medical care and are ideal for students who want to be involved in patient care. The duration of paramedical courses ranges from six months to two years, which is ideal for students looking to start working in the shortest time possible. Also, paramedics are an essential component of the healthcare system and hence a great career option as there is no dearth of jobs in this field. Another advantage of these courses is that paramedical courses can be pursued after completing Class 10.';
const p7 = 'Scope of work: Ideal for students who want to work at the ground level and create awareness among the population living in rural areas. Students will learn to provide assistance to those in need of medical attention and will learn how to provide first aid in such cases. They will also help create awareness about the various healthcare schemes of the government amongst these people, tell them about the common diseases and their prevention.';

// Vocational Courses //
const p8 = 'Vocational courses enable people to work that requires technical knowledge along with artistic or practical skills. These courses do not focus on theoretical knowledge, instead, they are primarily designed to provide job centered training for very specific fields. These include Healthcare, Mass Media, Designers, Makeup Artists among others. Before you look at the list of Vocational courses after the 12th, check out the step by step guide on skill development!';
const p9 = 'Physiotherapy Technician \nMedical Lab Technology course\nMarketing & Salesmanship\nAccounting & Taxation\nOffice Assistantship\nInsurance & Marketing\nBanking & Financial Services\nHospitality Management Courses\nFood & Beverage Services\nBakery & Confectionary\nCraft Course in Food Production\nCookery\nHousekeeping\nRestaurant & Counter Service\nHotel Reception & Bookkeeping\nBoutique Management\nJewellery Design\nSports Nutrition\nHR Management\nRetail Business\nPublic Administration\nAnimation\nRobotics\nAudio Technician\nInsurance\nLaw\nOffice Management';
const p10 = 'Vocational courses is helpful in a variety of industries, including design, makeup artistry, mass media, and healthcare. Instead of emphasizing theoretical knowledge, these courses give students the skills they need to succeed in their chosen fields.There are thousands of Vocational courses in different fields. Among the Vocational courses listed, Telecommunication, Photography, Foreign Languages, Information Technology (IT), Beautician, and Hotel Management are on the top';

// ITI Courses
const p11 = 'ITI Courses After 10th :- Industrial Training Institutes (ITIs) are government-funded education and vocational training institutes in India established to train unemployed youth with technical skills required for specific industries. ITIs offer diploma courses in engineering, architecture, construction and other related fields as well as certificate courses in trade skills such as mechanics, welding, carpentry, electrical, plumbing and more. With the increasing number of industries in India, ITI courses provide a promising career path for the aspiring youth to obtain ample job opportunities. Knowing about the importance of these courses for students in india is essential for any individual looking to make an informed decision in decisioning their future. Therefore, this article provides a comprehensive overview of the ITI courses in India, along with the types of ITI courses and admission details.';
const p12 = 'The ITI courses available after 10th Grade allow you to specialise in areas that you feel passionate about and gain skills that are in demand. From engineering and technical programmes to non-engineering and computer studies, ITI offers a diverse range of educational opportunities. Don\'t miss out on this great chance to kickstart your career and invest in yourself!';
const p13 = 'Communication Skills\nLeadership Skills\nCore Subjects Knowledge\nCreative Skills\nInnovative Skills\nCritical Thinking\nProblem-solving Skills\nAbility to Work Under Pressure\nTeamwork and Collaboration Skills';
const p14 = 'These ITI courses are designed for students who could be more economically strong and want to get into employment as soon as possible by learning technical and non-technical skills after the 10th. Here are some of the many advantages that an ITI course offers';
const p15 = '1) Easy employment:- After completing an ITI course, one can quickly get employment in the government and semi-government sectors. Government sectors include Railways, Army, Irrigation, Vocational Education Department, Technical Education Department, and Army Forces. Semi-government sectors include BHEL, Defence factory, HAL, SAIL, NTPC, ONGC etc.';
const p16 = '2) Land a job at the top private company:- After completing an ITI course, one can land in one of the leading firms such as Maruti Suzuki, Hyundai, Reliance, Aditya Birla, Honda, Infosys etc.';
const p17 = '3) Short courses:- These courses are shorter than some traditional courses.';
const p18 = '4) No need for a bachelor\'s degree:- Students wishing to pursue ITI courses do not have a bachelor\'s degree.';
const p19 = '5) Scholarships:- According to the rules of the State Government, students are given scholarships and fee reimbursement to the eligible candidates.';
const p20 = '6) Free ITI training: Students belonging to S.C./ S.T. categories are given free ITI training';

// UG Courses for Arts Students //
const b1 = 'Students who think that if they choose Arts Stream, they will have less career opportunities than science and commerce, but after completing 12th from arts, there is a list of courses which will provide you good career opportunities.';
const b2 = 'BBA- Bachelor of Business Administration\nBMS- Bachelor of Management Science\nBFA- Bachelor of Fine Arts\nBEM- Bachelor of Event Management\nIntegrated Law Course- BA + LL.B\nBJMC- Bachelor of Journalism and Mass Communication\nBFD- Bachelor of Fashion Designing\nBSW- Bachelor of Social Work\nBBS- Bachelor of Business Studies\nBTTM- Bachelor of Travel and Tourism Management\nAviation Courses\nB.Sc- Interior Design\nB.Sc.- Hospitality and Hotel Administration\nBachelor of Design (B. Design)\nBachelor of Performing Arts\nBA in History';
const b3 = 'It is always crucial that when you make a conscious choice of stream and subject you aspire and target the top universities/colleges. This will give you an enhanced learning environment as well as boost your career options and opportunities too.';
const b4 = 'While talking of top colleges and most sought-after targets for best courses after 12th Arts, DU always tops the list. To get into any top 10 DU colleges for Arts, you need to score really well in CUET as well as in your Boards. Keeping that in mind, a list of the top 10 DU colleges for Arts has been listed below. Go through them to have a holistic view.';

//UG Courses for commerce Students
const b5 = 'Students who want to learn about financial and management, can opt commerce stream after 10th. For commerce students, mathematics is an optional subject, thus students who have an interest in mathematics but do not want to go with science stream can take commerce with maths.';
const b6 = 'B.Com- Bachelor of Commerce\nBBA- Bachelor of Business Administration\nB.Com (Hons.)\nBA (Hons.) in Economics\nIntegrated Law Program- B.Com LL.B.\nIntegarted Law Program- BBA LL.B';
const b7 = 'CA- Chartered Accountancy\nCS- Company Secretary\nBachelor of Design in Accessory Design, fashion Design, Ceramic Design, Leather Design, Graphic Design, Industrial Design, Jewellery Design\nBachelor in Foreign Language\nDiploma Courses\nAdvanced Diploma Courses\nCertificate Courses';

// UG Courses available after 12th Science
const b8 = 'More often than not, students keep on wondering, what after 12th?  This problem especially becomes much more nuanced for pupils who opt for science stream in their +2.  Gone are the days when engineering and medicine were the only option available in the realm of science. With rising avenues in education every day, there are a wide array of courses available for learners after completing their 12th in science- both medical and non-medical. From courses in engineering, medicine, nursing, architecture, to law, liberal and fine arts, language and literature, students in science have numerous courses to choose from after 12th. As everyone is aware of, science stream can be divided into two sub streams: medical and non-medical. Numerous arrays of courses are available as an option for both the streams.';
const b9 = 'B.Tech/ B.E.\nB.Arch\nB.F. Tech\nB.Sc. (Hons.) Physics\nB.Sc. (Hons.) Chemistry\nB.Sc. (Hons.) Mathematics\nB. Sc. (Hons.) Zoology\nB. Sc. (Hons.) Botany\nB. Sc. (Hons.) Biology\nB. Sc. Microbiology\nB. Sc. Biochemistry\nB. Sc. Psychology\nB. Sc. Nutrition and dietetics\nB. Sc. Information Technology\nB. Sc. Food Science and Technology\nBachelor in Physiotherapy\nB. Sc. Anthropology\nMBBS\nB.Pharma\nBCA\nBasic Nursing Course\nBachelor of Dental Surgery (BDS)\nBachelor of Social Work\nBachelor of Physiotherapy\nBachelor of Homeopathy Medicine';
const b10 = 'Students have numerous options to choose from after 12th science PCM. Here is the list and details of courses one can pursue specific to 12th PCM. ';
const b11 = 'B. Tech or B.E.:- People who find themselves attracted to the development of upcoming as well as traditional methods of technology, can very well opt for the most sought after course after 12th in non-medical stream. Some of the sub-streams that one can opt to specialize in are';
const b12 = 'Civil Engineering\nEnvironmental Engineering:\nCeramic Engineering\nAerospace Engineering\nChemical Engineering\nIndustrial Engineering\nElectrical Engineering\nComputer Science Engineering\nAutomobile Engineering\nMechanical Engineering';
const b13 = 'With the need for medical professionals growing exponentially, the course pertaining to PCB have witnessed a wide surge in demand. PCB students often consider two-three options to pursue higher studies, rather, several other options are available to make a career. Following is the list of courses that one can pursue after 12th PCB.';
const b14 = 'MBBS: This is an obvious choice of course among the students after opting for PCB. Pursuing MBBS is a gateway for students to carve a landmark career in the field of medicine.';
const b15 = 'B. Pharma: A student can also get an entry into the world of medicine by pursuing bachelors in pharmacy. This course focuses on administering curriculum in a way that students learn the method and process that goes into producing certain medicinal drugs.';
const b16 = 'Bachelor of Dental Surgery: This course is a good choice for one to embark a journey to become a reputed dental surgeon.';
const b17 = 'B.Sc. Courses: Students can explore the specializations available in Bachelor of Science after their 12th in PCB. ';
const b18 = 'B. Sc. in Biology/Botany/Zoology\nB.Sc in Biotechnology\nB.Sc. Microbiology\nBachelor in Physiotherapy\nB. Sc. Nutrition and Dietetics\nB. Sc. Food Science and Technology\nB.Sc. in Biomedical Technology\nB.Sc. in Bioinformatics\nB.Sc. in Forensic Science\nB.Sc. Psychology';


// Courses after Graduation //
const g1 = 'Professional Courses mean providing students with industry-specific skills. A professional course provides students with practical skills. Students become job-ready after the course. In comparison, the goal of a degree course is to provide them with a strong academic foundation and expertise in a particular subject. The aim of these courses is skill-building, career development and self-improvement. This gives the students an edge over the others and also fosters creativity. Professional courses instill requisite soft skills in students that are much needed in the industry.';
const g2 = 'There are numerous job-oriented short-term courses as well as degrees you can explore after graduation. But picking the right program for your boosting your career can be a tough call. So, here is a list of top 10 best courses after graduation';
const g3 = 'PG Diploma in Management (PGDM)\nMBA (Masters in Business Administration)\nMTech\nPGD in Hotel Management\nPGPM\nCertification in Finance and Accounting (CFA)\nProject Management\nPG Diploma in Digital Marketing or Business Analytics\nBusiness Accounting and Taxation [BAT Course]\nMasters in Data Science or Machine Learning';
const g4 = 'If you don’t want to follow the typical route of an MBA, you can opt for a PGDM program which is another popular choice amongst the long list of professional courses after graduation. It equips an individual with essential knowledge of Business and Management concepts. Typically, it gears individuals for discovering job prospects in senior levels of Management. It also offers speedy career advancement opportunities to progress toward managerial or executive roles. Some of the popular PGDM courses are listed below';
const g5 = 'Becoming one of the popularly chosen courses after graduation, an MBA degree holds the potential of equipping you with massive industry exposure and skill set in your chosen field of interest. It features at the top of our list of professional courses after graduation owing to the wide range of MBA specializations available in every domain from Media Management and Interior Designing to Agribusiness and Entrepreneurship. Moreover, studying MBA from abroad avails you with extensive international exposure as well as networking opportunities to sail further in your field of interest.';
const g6 = 'With the rapid technological advancement tangling our world in wires and cables, an M.Tech degree is perfect for those wanting to discover the immense prospects that this technical domain holds. Often referred to as an equivalent to a ME (Master of Engineering) degree, the sole difference that sets an MTech apart is that it is more skill-oriented while the former is knowledge-oriented. Amongst the list of professional courses after graduation, MTech for working professionals is the right option for those aspiring to explore varied technical specializations such as Mechanical Engineering, Industrial Engineering, and Electrical and Electronic Engineering, amongst others.';
const g7 = 'Generally offered as a 1-2 year program, a Post Graduate Diploma in Hotel Management prepares students for managing roles in the hospitality industry. With the booming hospitality industry, establishing your career in Hotel Management comes with an array of exciting opportunities as you will get the chance to travel the world and work at top hotels, cruise ships, airlines, and much more.';
const g8 = 'As a one-year intensive postgraduate course, a Post Graduate Program in Management (PGPM) is ideal for those wanting to earn a professional master’s degree in lesser duration. With a rigorous curriculum, this course essentially focuses on the field of Management Studies and helps working professionals dwell deeper into this vast area of study. Incorporating an array of workshops and interactive learning into the structure is another significant mention in our list of professional courses because of the specialized knowledge it can equip you with regarding business and management.';
const g9 = 'This list of professional courses after graduation will be incomplete without the mention of Finance and Accounting courses. Prestigious certifications such as Chartered Accountancy (CA) or Chartered Financial Analyst (CFA) attract students from different backgrounds and aspiring for a faster route towards a career in Finance. Typically, you need to qualify through multiple levels of tests as well as a few minimum years of industry experience. ';
const g10 = 'Another key professional course you can pursue after graduation is a certification program in Project Management, for instance, an MBA in Project Management. Project management plays a pivotal role in ensuring effective management which can further lead to increased performance in a time-bound manner. Medical, Manufacturing, IT and Finance firms are always on the lookout for qualified project management professionals. The Project Management Professional Certification (PMP) is the most popular one in this field.';
const g11 = 'Amalgamating the specialized fields of Accounting and Taxation with the wider domain of Business, a BAT Course is a certified 6-month program that covers advanced concepts of Accounting, taxation payroll policies, and the integral disciplines of Economics. In the long list of professional courses after graduation, this interdisciplinary program can equip you with varied knowledge of handling the different aspects of business operations from account-keeping to managing funds and handling taxes.';

// Courses After Graduation: Diploma and Certificate //

const h1 = 'As we are familiar with the above-mentioned degree-based professional courses, given below are some of the popular diploma courses that one can pursue in a shorter duration as compared  to the above ones';

// List of Professional Courses after Graduation in Arts //
const h2 = 'While the aforementioned programs are the best job-oriented and high-salary courses after graduation for all streams of study, finding the appropriate specialisation for your chosen domain is also important. Here is a complete list of Professional Courses after Graduation in Arts';
const h3 = '1.Master of Business Administration (MBA)\n2.Master of Arts (MA) or Master of Fine Arts (MFA)\n3.PG Diploma/Masters in Journalism and Communication\n4.Bachelor of Education (BEd)\n5.Bachelor of Library Science\n6.Masters/PG Diploma in Digital Marketing\n7.LLB\n8.Foreign Language Courses\n9.PG Diploma in Management (PGDM)\n10.PG Diploma in Business Analytics (PGDBA)\n11.PG Diploma in Digital Marketing\nPGDEMA';
const h4 = 'Career Options with Courses After B.A';
const h5 = '[1] Pursuing a Degree in M.A.\n[2] Career as a Software Developer\n[3] Career in Business Analytics\n[4] Specialization in Data Science\n[5] Career in Digital Marketing\n[6] Career as a Human Resource Specialist\n[7] Career in Artificial Intelligence\n[8] Cybersecurity Specialization\n[9] Career in Graphic Designing\n[10] Career in Robotics';
const h6 = 'MA is one of the most preferred postgraduate degrees that students opt for amongst courses after BA. Master of Arts is a two-year program offered in a varied range of fields such as English, Hindi, Political Science, Journalism, Mass Communication, Regional and Foreign Languages, Fine Arts, Media, History, Philosophy, etc. A master’s degree aims to equip students with excellent academic knowledge and exposure to their field of interest. After completing an MA, you are qualified for M.Phil and doctoral programs as well.';

// List of Professional Courses after Graduation in Science //
const h7 = 'There are a plethora of professional courses after graduation in the Science stream that you can choose from like a Master’s degree in Science, MTech, Engineering Management, and Educational Technology, to name a few. Here are the top professional courses after graduation in Science';
const h8 = 'Master of Science (MS/MSc)\nMaster of Technology (MTech)/Master of Engineering (MEng)\nMaster of Computer Applications (MCA)\nMaster in Computer Science\nPG Diploma in Business Analytics\nParamedical Courses\nPG Diploma in Hospital Management/Hospital Administration\nMBA (Master of Business Administration)\nFinancial Engineering Courses\nMobile App Development Courses\nRobotics Engineering Courses';

// List of Professional Courses after Graduation in Commerce
const h9 = 'Looking for the best job-oriented course after B.Com, BBA, or BMS? Commerce is a vast field of study expanding across varied other disciplines and many specializations sprouting from it! Here are the most popular high-salary professional courses after graduation in Commerce';
const h10 = '[1] Chartered Accountancy (CA)\n[2] M.Com\n[3] MBA\n[4] MCA\n[5] PGDCA (Post Graduate Diploma in Computer Applications)\n[6] Chartered Financial Analyst (CFA)\n[7] Business Accounting and Taxation (BAT)\n[8] Tally Course\n[9] Masters in Digital Marketing\n[10] PGDM in Finance\n[11] PGDEMA\n[12] Certification Courses for Commerce Students like Certificate in E-commerce, Certificate in Banking, Certificate in Accounting, etc.';












